### ISSUE TITLE
Add support for importing closed issues

### ISSUE THREAD

**Issue by IQAndreas** [IQAndreas/github-issues-import#12]
There have been several requests for supporting closed issues, I'm wondering how people's projects are set up, why they would want already resolved issues in the target repository?

Also, for the final product, should issues that are closed in the source repository also be closed in the target repository, or should there just be a little "notice" saying _"This issue was closed 2013/10/26"_?

**Comment by tskulbru** [comment]
I want to be able to "clone"/"complete backup" a repo, and as such I need to bring the closed issues over as well. This is basically only for historicial purposes, The "notice" idea you mention sounds good.

The only important things really are that the closed issues remain closed when copied over, and also that the issue numbering is correct (for comments linking to issues etc.)

**Comment by IQAndreas** [comment]
> and also that the issue numbering is correct (for comments linking to issues etc.)

That is a really good point! We had a problem with that in one of my projects, and just ended up with a workaround of specifying things like "Fixes `AdamAtomic/flixel#3`, `FlixelCommunity/flixel#65`". I have put on my todo list that the script should warn the user if the numbering won't match once they import the issues (this may happen if they don't import all issues, or if the target repository already has issues in it).

> The only important things really are that the closed issues remain closed when copied over

Alas, I couldn't find a way in the API to close issues from a script, however, I did add a change which makes these issues stand out more by starting with the title `[CLOSED]`. Luckily, GitHub allows you to close several issues at once "checklist style" (without even having to open each issue's page). You can also easily edit the title if you want to re-open the issue later.

However, I will try to find a better solution for this, as well as adding some more notices: https://github.com/IQAndreas/github-issues-import/issues/14

**Comment by IQAndreas** [comment]
Added in 3a400c77ee85228b1b4e05eccf5f6477723aa1f2
