### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by IQAndreas** [IQAndreas/github-issues-import#13]
Surprisingly difficult, as there are so many to choose from, and it's difficult find non-legalese explanations for them.

**Comment by tskulbru** [comment]
Thought I could share some bookmarked links on the matter: 
- http://choosealicense.com/
- http://www.tldrlegal.com/compare

**Comment by IQAndreas** [comment]
Added in f1c655f665328ccea135d53d5d827284317f1cfe

_GitHub Issues Importer_ is now released under [_the MIT License_](https://github.com/IQAndreas/github-issues-import/blob/master/LICENSE.md) (Markdown-formatted version of the MIT license courtesy of another side project of mine, [Markdown Licenses](https://github.com/IQAndreas/markdown-licenses/))

**Comment by asmeurer** [comment]
Good choice.
