### ISSUE TITLE
Test if script works with "Two-Factor Authentication"

### ISSUE THREAD

**Issue by IQAndreas** [IQAndreas/github-issues-import#22]
I haven't tested to see if the script is able to import issues if the account running the script requires two-factor authorization. See:
- [GitHub Help: About Two-Factor Authentication](https://help.github.com/articles/about-two-factor-authentication)

Also, all the more reason to [use an API key](https://github.com/IQAndreas/github-issues-import/issues/21) instead of storing using passwords.

**Comment by asmeurer** [comment]
It doesn't.

**Comment by IQAndreas** [comment]
> It doesn't.

Thanks for testing, I'll have to add that feature in the near future.
