### ISSUE TITLE
Example issue with comments

### ISSUE THREAD

**Issue by IQAndreas** [IQAndreas/github-issues-import#3]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed posuere neque eros, eu varius nisl volutpat ac. In hac habitasse platea dictumst. Maecenas in leo eget massa placerat porttitor nec sed justo. Quisque laoreet egestas dui tristique dignissim. Integer porttitor venenatis porttitor. Vestibulum urna ipsum, aliquam accumsan ante vitae, lacinia laoreet lectus. Proin suscipit nisl aliquam mollis elementum. Nulla ac feugiat nunc. Cras a dictum dui, at pellentesque massa. Sed accumsan accumsan tortor, sed auctor massa rutrum eu. Nunc et mollis nisi. Vivamus ac nisl iaculis, commodo mi non, sagittis orci. Nullam consequat nec nisi quis volutpat. Etiam at purus sit amet nibh consequat dapibus id et arcu. Duis ut leo id dui pretium ullamcorper. Nullam eget suscipit lorem.

Vestibulum tristique tortor a erat sodales, sed molestie sapien accumsan. Ut convallis diam vitae nunc fringilla convallis. Curabitur malesuada risus a consequat pharetra. Curabitur commodo, nibh vitae ullamcorper dapibus, turpis risus suscipit risus, ut porta odio risus et mauris. Praesent hendrerit felis at eros cursus, sed pharetra ligula suscipit. Vestibulum faucibus velit id consectetur adipiscing. Morbi cursus pellentesque fermentum. Cras porta purus sed placerat tincidunt. Nunc imperdiet, leo et dictum vulputate, nisl risus molestie lacus, in tristique diam ipsum id sem. Phasellus sit amet tristique erat, id ornare urna. Sed sollicitudin, diam eget cursus mattis, purus turpis aliquet velit, a eleifend magna turpis vitae dui. Cras nec lectus odio. Donec non felis pharetra urna posuere scelerisque.

**Comment by kirupa** [comment]
lorem ipsum

**Comment by IQAndreas** [comment]
> lorem ipsum

Aenean arcu erat, pharetra sed consectetur id, faucibus sed erat. In tincidunt scelerisque luctus. Etiam vitae orci sagittis, bibendum justo et, tempor tortor. Can't tell if my instructions were unclear, or you are being lazy or a smartass. Pellentesque commodo placerat luctus. Sed vitae elit ac arcu auctor pellentesque et et sapien.

**Comment by krilnon** [comment]
![fmrmpjl](https://f.cloud.github.com/assets/509626/1146844/395ce87e-1e82-11e3-889b-18bfd189a50f.jpg)
