### ISSUE TITLE
Unable to find config 'none'

### ISSUE THREAD

**Issue by as3boyan** [IQAndreas/github-issues-import#30]
```
--config 'none'
```

**Comment by IQAndreas** [comment]
We switched to using a `--no-config` flag instead (see 243ab9f894259327b8647ed2ea400c32287e6d4e). Sorry, I may have forgotten to update the README with that new information. I'll fix that once I'm back from my trip.

**Comment by IQAndreas** [comment]
Fixed by [**as3boyan**](https://github.com/as3boyan) in a6689dbc7ead4aaf41c1935f4a4856133d06ac64
